plugins {
    id 'java'
    id "com.gradleup.shadow" version "9.3.0"
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.3'
}


configurations {
    implementation.extendsFrom shade
}

repositories {
    maven { url "https://maven.hytale.com/release" }
    maven { url "https://cursemaven.com" }

    flatDir {
        dirs("libs")
    }
}

dependencies {
    implementation 'com.hypixel.hytale:Server:2026.01.28-87d03be09'

    //compileOnly("curse.maven:simpleclaims-1405415:7540330") // 1.0.25
    implementation("curse.maven:multiplehud-1423634:7530266") // 1.0.4

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

shadowJar {
    configurations = [project.configurations.shade]
    mergeServiceFiles()
}

test {
    useJUnitPlatform()
}

processResources {
    var expandProps = [
            'name'       : project.name,
            'version'    : project.version,
            'group'      : project.group
    ]

    filesMatching(['manifest.json']) {
        expand expandProps
    }
}

def serverRunDir = file("$projectDir/run")
idea.project.settings.runConfigurations {
    'HytaleServer'(org.jetbrains.gradle.ext.Application) {
        mainClass = 'com.hypixel.hytale.Main'
        moduleName = project.idea.module.name + '.main'
        programParameters = "--allow-op --disable-sentry --assets=\"/Users/tomalbrecht/Library/Application Support/Hytale/install/release/package/game/latest/Assets.zip\" --mods=${file("src/main/").absolutePath} --auth-mode=authenticated"
        workingDirectory = serverRunDir.absolutePath
    }
}
